#!/usr/bin/env ruby
#
# dump_s3_bucket 0.1 - 2009-10-20
# by Paul Mylchreest (paul.mylchreest@mac.com)
#
# This script allows you to dump a s3 bucket into the current directory.

# dump_s3_bucket bucket access_key secret_access_key

require 'rubygems'
require 'aws/s3'

def bucket_name
  a ||= ARGV[0] if ARGV.size > 0
  a ||= ENV['BUCKET']
end

def directory
  a ||= ARGV[1] if ARGV.size > 1
  a ||= ENV['DIR']
end

def access_key
  a ||= ARGV[2] if ARGV.size > 2
  a ||= ENV['AMAZON_ACCESS_KEY_ID']
end

def secret_access_key
  a ||= ARGV[3] if ARGV.size > 3
  a ||= ENV['AMAZON_SECRET_ACCESS_KEY']
end

def establish_s3_connection
  AWS::S3::Base.establish_connection!(
    :access_key_id     => access_key,
    :secret_access_key => secret_access_key
  )
end

establish_s3_connection

puts "Bucket: #{bucket_name}"
bucket = AWS::S3::Bucket.find bucket_name
puts "Bucket size: #{bucket.objects.size}"

bucket.objects.each do |o|
  filename = [directory, bucket_name, o.key.split('/')].join('/')
  dir = filename.split('/')[0..-2].join('/')
  %x[mkdir -p #{dir}]
  open(filename, 'w') do |file|
    puts "Dumping #{o.key} to #{filename}"
    AWS::S3::S3Object.stream(o.key, bucket_name) do |chunk|
      file.write chunk
    end
  end
end
