#!/usr/bin/env ruby
#
# get_s3_object 0.1 - 2009-10-01
# by Paul Mylchreest (paul.mylchreest@mac.com)
#
# This script allows you to download a s3 object to a file.

# get_s3_object bucket filename s3_key access_key secret_access_key
# See http://amazon.rubyforge.org/

require 'rubygems'
require 'aws/s3'

def bucket
  a ||= ARGV[0] if ARGV.size > 0
  a ||= ENV['BUCKET']
end

def filename
  a ||= ARGV[1] if ARGV.size > 1
  a ||= ENV['NAME']
end

def s3_key
  a ||= ARGV[2] if ARGV.size > 2
  a ||= ENV['S3_OBJECT']
end

def access_key
  a ||= ARGV[3] if ARGV.size > 3
  a ||= ENV['AMAZON_ACCESS_KEY_ID']
end

def secret_access_key
  a ||= ARGV[4] if ARGV.size > 4
  a ||= ENV['AMAZON_SECRET_ACCESS_KEY']
end

def establish_s3_connection
  AWS::S3::Base.establish_connection!(
    :access_key_id     => access_key,
    :secret_access_key => secret_access_key
  )
end

establish_s3_connection

open(filename, 'w') do |file|
  puts "Bucket: #{bucket}"
  puts "Filename: #{filename}"
  puts "Key: #{s3_key}"
  AWS::S3::S3Object.stream(s3_key, bucket) do |chunk|
    file.write chunk
  end
end
